### ISSUE TITLE
upon deploy.js → UnhandledPromiseRejectionWarning: Error:

### ISSUE THREAD

**Issue by mesqueeb** [DRI-network/RICO#33]
There is an issue with the promise returned from `const wallet` in the deploy script.

Problematic line:
```js
const wallet = await MultiSigWalletWithDailyLimit.new([multisigWalletAddress1, multisigWalletAddress2], 2, multisigWalletDailyLimit)
```
Error in console:

> (node:34173) UnhandledPromiseRejectionWarning: Error: VM Exception while processing transaction: revert
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:41484:16)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:329530:36
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:325200:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:328229:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176415:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176705:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176860:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176820:24)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
(node:34173) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:34173) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mesqueeb** [comment]
Thanks, we're looking into it now! :D

**Comment by mesqueeb** [comment]
https://github.com/gnosis/MultiSigWallet/issues/82

**Comment by mesqueeb** [comment]
Please change
```js
const wallet = await MultiSigWalletWithDailyLimit.new([multisigWalletAddress1, multisigWalletAddress2], 2, multisigWalletDailyLimit)`
```
to 
```js
const wallet = await MultiSigWalletWithDailyLimit.contract.new([multisigWalletAddress1, multisigWalletAddress2], 2, multisigWalletDailyLimit)
```

**Comment by mesqueeb** [comment]
https://github.com/DRI-network/RICO/commit/00b0743dd4021d77a9f59f033de1bdfd5cdca7a2
